import csv
import json
import os
import time
import typing
from collections import OrderedDict
from datetime import datetime

import pandas as pd
import requests
import zipfile

# This script downloads the latest TNS data from the website and filters 
# the newly added or recently modified objects based on predefined criteria.

# url to the webpage where you can download the daily csv file 
URL_TO_DAILY_CSV = 'https://sandbox.wis-tns.org/system/files/tns_public_objects/tns_public_objects.csv.zip'

# you can find those details on your bot's edit page
TNS_BOT_ID          = "167012"
TNS_BOT_NAME        = "trial_bot"
TNS_API_KEY         = "be3ee6320999824f413f65be89d22e27684f0653"

#Here you can define the date you want to filter the data by
wanted_date =  datetime(2023, 12, 3)

def set_bot_tns_marker() -> str:
    """
    this function sets the request header (-H) according to the TNS documentation:
    using the bot's details
    """
    tns_marker = 'tns_marker{"tns_id": "' + str(TNS_BOT_ID) + '", "type": "bot", "name": "' + TNS_BOT_NAME + '"}'
    return tns_marker

def get_data_from_tns(tns_marker:str) -> any:
    """
    this function sends a request to the website where the daily csv file can be found
    (according to the url you inserted).
    gets the tns_marker that the set_bot_tns_marker func generates and returns the content
    of the response if it gets one and None otherwise
    """
    headers = {
    'user-agent': tns_marker
    }
    data = {
    'api_key': TNS_API_KEY
    }
    response = requests.post(URL_TO_DAILY_CSV, headers=headers, data=data)

    # Check the response status
    if response.status_code == 200:
        # The content of the response (the downloaded file) can be accessed using response.content
        print('data downloaded successfully.')
        return response.content
    else:
        print(f'Error downloading file. Status code: {response.status_code}')
        print(response.text)  # Print the response content for further inspection if needed
        return None

def response_data_to_df(data: any) -> pd.DataFrame:
    """
    this function converts the response from the TNS website into pandas' dataFrame
    args: data - the content of the response (response.content that generated by get_data_from_tns)
    return value: dataframe
    """
    with open('tns_public_objects.zip', 'wb') as f:
            f.write(data)
        # extracts the file and creates a DF from it
    with zipfile.ZipFile('tns_public_objects.zip', 'r') as zip_file:
        with zip_file.open('tns_public_objects.csv') as csv_file:
            df = pd.read_csv(csv_file,sep=",",index_col=False, skiprows=1, parse_dates=[20])
            return df

def last_modified_filter(df: pd.DataFrame) -> pd.DataFrame:
    """
    this function filters only the classified data from the date specified and after it
    (using "lastmodified" column in the downloaded csv)
    arg: dataframe to sort
    returns: new sorted dataframe
    """
    rslt_df = df[df['lastmodified'] > wanted_date]
    modified_df = rslt_df[rslt_df['type'].notna()]
    return modified_df

def types_filter(df: pd.DataFrame, attr1: str, attr2:str) ->pd.DataFrame:
    """
    this function filters the the type of the classified objects according to attr1 and attr2
    (using "type" column in the downloaded csv) 
    args: df- dataframe to filter, attr1- one type you want will remain
    attr2- other type you want will remain
    return: new sorted dataframe
    """
    # this is the code to filter the df by the content of "type" column
    # it's a or expression, so if you want to see other types too you can extend it 
    # by adding "| df['type'].str.contains(attr3, case=False)" here and more attrs to the function
    filtered_df = df[df['type'].str.contains(attr1) | df['type'].str.contains(attr2, case=False)]
    
    return filtered_df

def export_to_csv(df: pd.DataFrame):
    """
    this function creates a csv file from a dataframe
    """
    filtered_data_path = f'daily_filtered_data.csv' #the name of the generated file
    df.to_csv(filtered_data_path, index=False)


def main():
    tns_marker = set_bot_tns_marker()
    data = get_data_from_tns(tns_marker)
    if data: #if not - there is an error in the response
        df = response_data_to_df(data)
        modified_df = last_modified_filter(df)
        if not modified_df.empty:
            typed_df = types_filter(modified_df,'SN','TDE')
            export_to_csv(typed_df)
        else: print(f"there were no SN or TDE classifies since {wanted_date}")

   

if __name__ == "__main__":
    main()
